### ISSUE TITLE
Returning to Site Shortly after Left

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#100]
I noticed that when I returned to the site after leaving, it just showed a screen that said "you are currently logged in"....any way to have this show up as View Applications? Or, could we have the site auto log-out a user after they leave the site/close the window?

**Comment by tbstevens** [comment]
@Creekridge  - Good catch there. We'll have to figure out what the best approach is on this one. We can add to the list for Thursday's meeting. It's taking all users back to the one public login page at the portal site. We could make a change to force a redirect to the site home page for site level users, but for portal level users we wouldn't know which site to redirect to.

**Comment by tbstevens** [comment]
Closing out this issue in replacement of a new issue the describes what the desired feature is (To redirect vendor site users to their site if they hit the main portal page)
