### ISSUE TITLE
Payment Calculator: Price Field "$" Sign

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#101]
Issue:
------------
Equipment price doesn't format with a $, commas, and decimal until after the user chooses to continue into credit app.

Expected
-------------
Equipment price should be formatted with a $, commas, and decimal after the user tabs off the field or presses calculate. 

Notes: Field needs to be masked with $, commas, and decimal in the correct places without impacting the calculation for monthly payment amount.

**Comment by tbstevens** [comment]
The $ sign does appear with commas and decimal point once you calculate the value. Having it format after the field loses focus would be more complex as it would require the value to be trimmed of characters for the calculation and then reapply the characters after calculation. Is it acceptable for the equipment price to appear with $, commas and decimals after pressing the calculate button? It also shows before calculation when you come into the screen from a saved application.

**Comment by Creekridge** [comment]
@tbstevens got it, leave it as-is. Just wanted to make sure it was cleaned up at some point. Thanks!

**Comment by Creekridge** [comment]
@tbstevens can we look into having the field ad comma's and periods? Maybe we could just put a "$" sign prior to the field???

**Comment by Creekridge** [comment]
@tbstevens or could the format just be a mask?

**Comment by tbstevens** [comment]
@creekridge - Let me make sure I understand this request before taking it to the developer. 
The site currently takes a value entered by a user and reformats it after pressing calculate. I believe up above it was decided to just move forward with that but perhaps based on feedback, are we now deciding the formatting is needed as the user enters the value? More specifically, we need to make a change so that the $, commas, and decimals appear as the user enters the equipment price?

**Comment by Creekridge** [comment]
Production isn't reformatting it at all.  We would prefer it to reformat immediately as our old site does, but if it isn't possible, we'll live with reformatting on calculate.

**Comment by tbstevens** [comment]
@Creekridge  - Just went out to production. I misspoke. The reformatting occurs after you choose to move forward with the calculation and into the credit app. Once you move into the credit app by selecting a pricing option and clicking continue, the equipment price in the payment calculator section appears with $, commas, and decimal. It also appears this way when coming in from a saved app in production. I'll assign this to our developer to format the field so it formats on calculation.

**Comment by tbstevens** [comment]
@OlegForce  - Assigned this to you. You can ignore the commentary below the description of this issue. I updated the description to contain the info you need. Let me know if you have questions.

**Comment by tbstevens** [comment]
@olegforce - Re-tested. Equipment price doesn't show as formatted when you tab out or at calculation or at entry. The formatting doesn't show up until after you continue into the credit app.

**Comment by OlegForce** [comment]
how about now?
