### ISSUE TITLE
Payment Calculator: Required Field Error Message

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#103]
Any way to include the heading in the error message. Right now it reads "Address Line 1: This field is required." and I'm not sure where it's at unless I scroll through and see the red (It could be customer address, principal address, bank address). Can we make this a little more clear and have it read "Customer Address Line 1: This field is required."

**Comment by tbstevens** [comment]
@OlegForce - Would it be pretty quick for you to modify the error messaging if I provided you with a spreadsheet mapping each field to a field category so the error messages could include the field category in the error messaging? Alternatively, I could just provide an update to each error message to plugin. Let me know.

**Comment by OlegForce** [comment]
I use js to figure out the section name based on field location. Give it a shot and let me know if that works.

**Comment by tbstevens** [comment]
Looks good to me. Re-opening this one to allow Creekridge to test it.

**Comment by Creekridge** [comment]
@tbstevens I'm not seeing the section name on in the errors. Still reads "Address Line 1 : This field is required."

**Comment by tbstevens** [comment]
@Creekridge - Sorry, it hasn't been deployed yet. I'll assign this to myself until it is deployed to prevent confusion.

**Comment by Creekridge** [comment]
@tbstevens sounds good, thanks!

**Comment by tbstevens** [comment]
@Creekridge - deployed the changes. The new error messages should now appear to re-test.

**Comment by Creekridge** [comment]
@tbstevens looks good. Thanks for fixing this issue!
