### ISSUE TITLE
View Mobile/Tablet Versions

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#104]
@tbstevens can we see what the site will look like when viewed on Mobile/Tablet on Thursday?

**Comment by tbstevens** [comment]
@Creekridge  - yes. Also, if you wanted to emulate it, Liferay does have an option when you login as an admin to see what it would look like from the perspective of a smartphone or tablet. On the left dockbar (floating blue menu on the left) there is an icon that looks like a monitor. You can change it to tablet or smartphone to see what it would look like.

**Comment by Creekridge** [comment]
@tbstevens I'm trying to log in as admin, but my "mgannott@creekridgecapital.com" isn't working with the password you emailed over before. Please assist.

**Comment by tbstevens** [comment]
@Creekridge - You should receive an email with your password reset. I'll also email you in case you don't receive it. If you don't receive it, let me know because that would be an issue we should log.

**Comment by Creekridge** [comment]
@tbstevens  no email, but it worked when I tried to log-in and got to reset it. Please log issue.
