### ISSUE TITLE
Edit All Vendor Sites for Both Sandy an Megan

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#106]
@tbstevens this is Megan. When I log in as admin, I can edit information on the "Sample Vendor 1" site, but unable to edit stuff (logo, etc.) on the "Vendor Services Group" site. Sandy and I both need access to edit all Vendor websites.

**Comment by tbstevens** [comment]
@creekridge - Hi Megan. Could you logout and log back in to see if you now have correct permissions? It looks like Sandy was setup as a portal admin but you were not. I modified you to also be setup as a portal admin.

**Comment by tbstevens** [comment]
@creekridge - Hi Megan - did you confirm whether or not you're now able to edit the Vendor Services Group site as an admin?

**Comment by Creekridge** [comment]
@tbstevens yes, I can now edit the page as admin.
