### ISSUE TITLE
Set Up Creekridge Sales Managers

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#107]
@tbstevens we're assuming this will be included in Thursday's meeting, but just logging it to make sure! These are our Sales Managers who will need access to see deals via different vendors.

**Comment by tbstevens** [comment]
@creekridge - 

Yep, part of the meeting on Thursday. Until then:

1. Click on Admin
2. Click on Users and Organizations
3. Click on Add +
4. From dropdown, select Add User.
5. Enter details for user.
6. Click Save
7. Pressing Save takes you to the Edit User screen with more options.
8. From the right panel, click on Password and set a temp password.
9. From right panel, click on sites, and assign the user to the vendor sites you'd like them to belong to.
10. Click save (important step so you can set role after save).
11. From right panel, click on Roles. Select Creekridge Manager.
12. Click save.
13. If that particular user is the rep for a specific site, setup that user to receive submitted application emails by going to Sites > Click on specific site > Configuration from Left Panel > Site Settings > Custom Fields > Enter email address in "Rep Email".

**Comment by Creekridge** [comment]
@tbstevens thanks!
