### ISSUE TITLE
Credit App PDF

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#108]
@tbstevens let's put this on tomorrow's topic to talk about: making the Credit App PDF to fit on one page (preferred)..maybe two. Three pages seems to get to be too much.

**Comment by Creekridge** [comment]
Also - this is the old version - not the one we sent to you on the 19th.

**Comment by tbstevens** [comment]
@Creekridge - the credit application is part of the discussion on Thursday -- included with the list of other enhancements.

**Comment by tbstevens** [comment]
Closed -- topic for meeting on 1/8
