### ISSUE TITLE
Equipment Discription Field

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#113]
This still hasn't been moved. We'd like it to the left of the Equipment price.

**Comment by Creekridge** [comment]
Or just below the Equipment price if it cannot go to the left.

**Comment by OlegForce** [comment]
moved it to the left of price, but had to make it a regular input field vs text area for esthetics.

**Comment by Creekridge** [comment]
@tbstevens looks good!
