### ISSUE TITLE
Mask Social Security Numbers

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#115]
Enhancement Request:
-------------------------------
Principals already added to the application should have their SSN masked.

Requirements
----------------------------------
1. On the Application edit screen, after adding a principal from the modal, if an SSN has been entered on the principal, it should be displayed on the screen as XXX-XX-9999 with only the last 4 digits displayed on the screen.
2. On the Application view only screen, principals with SSNs should also have SSN masked using the same format.

**Comment by tbstevens** [comment]
@creekridge - This one wasn't on the original list. It would take 30-60 min to mask the SSN on the principal. Also, would you want to mask the Federal Tax ID on the Customer section as well? If so, we'll just have to get the mask you'll want for that. The mask on SSN for principal will be xxx-xx-9999.

**Comment by tbstevens** [comment]
@Creekridge - tested in prod and working. I'll let you confirm.

**Comment by Creekridge** [comment]
Confirm -SSN is being masked as described above.
