### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#116]
We need to make sure the set required fields. Many are not set yet.

** Modified to include issues that require resolution **

Issue:
-------------
Not all required fields are listed as required.

Expected:
----------------
**Customer section**
1. Phone (Contact section) is a required field.
2. Zip (Customer Address) is a required field.

**Principal section** 
The fields listed below shall appear as required fields in the principal modal (label includes *). The validation should only occur within the principal modal at the time where the principal is added. It should not be validated on an application save or submit because there are 0 to many principals per app.
1. First Name
2. Last Name
3. Home Phone
4. Address Line 1
5. City 
6. State
7. Zip

Bank references section may have requirements added at a later time. These will be added as a new enhancement if needed.

**Comment by tbstevens** [comment]
@Creekridge - Is this in reference to the credit application or another screen?

**Comment by Creekridge** [comment]
@tbstevens in the Payment Calculator as information inputted into Customer Information, Principal and Bank fields.

**Comment by tbstevens** [comment]
@Creekridge - Let me know which fields in the customer section are not listed as required and we can update. For principal and bank, that could be a little more complex. Is it required to have at least one principal included and at least one bank reference included? If not, should specific fields be required only if the user has decided to add a principal or bank reference?

**Comment by Creekridge** [comment]
@tbstevens the required fields we had on our old site are the same for this one. We do not require at least one principal or bank reference. However, we would need specific fields to be required only if the user as added them, which are also shown on our old site.

**Comment by tbstevens** [comment]
@creekridge -- I updated the description of this issue to include the specific modifications required to fulfill the expected required fields. Could you confirm that this is accurate? I used your existing site to determine where the gaps were. I did not see any required fields in the existing site for bank references. I had missed the principal section requirements because they don't appear with any indication that they are required on the field labels.

**Comment by Creekridge** [comment]
Please add email to Customer required fields.  Our current site doesn't have any required fields for Bank reference - I'll need to check and see if we want to require any.  Principals look correct.

**Comment by OlegForce** [comment]
let me know if print out of errors in modal is not required.

**Comment by tbstevens** [comment]
@OlegForce - Looks like everything is good except for the fact that I missed making email a required field in the customer section. Sorry, one more change to make email required in the customer section.

**Comment by OlegForce** [comment]
did you mean in principal section for this one? 
@tbstevens

**Comment by OlegForce** [comment]
I guess not.

**Comment by Creekridge** [comment]
@tbstevens looks good.
