### ISSUE TITLE
UI Improvements for View Applications page

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#117]
Issue:
------------------
1. Too many filters.
2. Filters are not desired on left part of page -- takes up too much real estate.
3. Page needs to be responsive. 
4. Page needs to display correctly in all major browsers -- Chrome, IE, Firefox, Safari
5. Table grid could look nicer.

Expected
----------------
1. Filters should appear horizontally above the grid of applications.
2. There should only be one filter is the user is a sales rep -- Application Status. It should default to "Saved". The options in the Status dropdown should include "Saved", "Submitted", "Cancelled", or "All". Selecting all would display all 3 statuses. Draft status should never appear in the screen.
3. For all other user roles, an additional filter should appear titled "Sales Rep". This would include a dropdown of all users with the Sales Rep role for the vendor being viewed. Selecting this would filter the application grid to only display applications for that sales rep.
4. Page should resize to fit on page for smartphone, tablet, or any desktop resolution.
5. Table should use bootstrap styling for alternating row colors.
6. Screen should display appropriately in all browsers.

**Comment by tbstevens** [comment]
Already logged as a bug with the firefox issue - developer working on fix.

**Comment by Creekridge** [comment]
@tbstevens please be aware it's also happening in Safari

**Comment by OlegForce** [comment]
give it a shot. I know it displays Drafts as well... noticed it later after committed. Not sure why we don't want to show those... Makes sense to be able to see them. No?

**Comment by tbstevens** [comment]
@Creekridge - The look of this page was improved, feel free to take a look at it. Please confirm if you would like "Draft" removed from the dropdown. I was going to ask for it to be removed but I'll confirm with you first. Also to note -- There is additional work in progress to have the Sales rep dropdown and Sales rep column appear in this version. Should be ready by end of week.

**Comment by Creekridge** [comment]
@tbstevens please remove Drafts from dropdown and from what is view from the user on the site. We only want them to see "Saved", "Submitted", "Cancelled", or "All".

**Comment by tbstevens** [comment]
@Creekridge - Ok, I'm going to close this issue and open a new issue based on the comment above.
