### ISSUE TITLE
Logo size in Mobile/Tablet Version

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#118]
The logo size is so small you cannot read it.

**Comment by tbstevens** [comment]
@Creekridge - I'll work with the developers to determine if there is a way to prevent this from occuring. The site logo and responsiveness of the logo are based on the standard Liferay styling.

**Comment by psakia** [comment]
@tbstevens - The log image is jpg format. Can we change the logo format to png format ? Liferay has some issues with jpg which I'm not sure have been resolved.

**Comment by tbstevens** [comment]
@Creekridge - are you able to use .png files for the logos?

**Comment by Creekridge** [comment]
@tbstevens Megan emailed this to you.

**Comment by Creekridge** [comment]
@tbstevens most of our vendor logs are in JPG, so this would still be an issue on their site. We typically have a tough time getting any other versions of logos from our vendors.

**Comment by tbstevens** [comment]
@psakia - Loaded png logos to the site. Same issue. cleared cache to make sure it wasn't the same jpg image. As creekridge stated above, most of the logos will be jpeg. Any available fix for jpegs?

**Comment by tbstevens** [comment]
@Creekridge - We have a fix for this (tested in local environment). I need to deploy the updates to the existing theme file to deploy and test in production. Is there a new method for deploying these files to the server now that it is in the DMZ? I can no longer access CRCVIP through remote desktop.  Thanks!

**Comment by Creekridge** [comment]
Tom,

Use the IP 192.168.5.20 instead of the server name in the Remote Desktop Connection.

Sandy

**Comment by tbstevens** [comment]
Sorry Sandy, it doesn't seem to be working. https://www.dropbox.com/s/bsai6a6qr0hfbs9/remotedesktopmessage.png?dl=0

**Comment by Creekridge** [comment]
@tbstevens  you should be able to access this now

**Comment by tbstevens** [comment]
@Creekridge - This is now ready to be tested in prod. The change that was made was to the responsive css file that controls the entire liferay framework. The responsive file was restricting the width of logos to 35px when it moved into mobile view. That restriction was modified to 100px of width. You will notice that the logo does get smaller to ensure there aren't width issues on mobile size screens but that the logo now has a minimum of 100px of width vs 35px. Let me know if you have any questions.

**Comment by Creekridge** [comment]
@tbstevens - still looks a little small to me, but this one is really Megan's call.  She's out until Monday so we'll take a look at it then.

**Comment by tbstevens** [comment]
@Creekridge - We can adjust the minimum width requirement to whatever you consider the most optimal. Another thing to consider is whether or not you'll have any logos that are more square in dimension. If the width limitation is set to say, 200px, a square logo would also result in 200px of height. That would take up a lot of vertical real estate on a mobile screen. A rectangular logo wouldn't be a height impact.

**Comment by Creekridge** [comment]
@tbstevens Looks good. Thanks!
