### ISSUE TITLE
Save application when Manage Document button is pressed

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#121]
Issue
----------
When a user fills out some fields and then presses on Manage Docs, all data entered on the application is lost.

Expected
------------
When pressing the Manage Docs button, the application is validated and saved prior to moving the user to the Manage Documents screen.

Note: The enhancement request to auto-save or save on leaving the screen (regardless of method of leaving screen) is a separate issue.

**Comment by OlegForce** [comment]
validates and saves app on click now.

**Comment by tbstevens** [comment]
@OlegForce - Re-tested. Clicking on manage docs properly validates all required fields, but after entering all necessary data, pressing manage docs button again results in error. Unable to finish testing.

Results in error on screen stating "Payment Calculator is temporarily unavailable". 

The error message from Eclipse is attached. I was able to recreate this 3 times out of 3.

**Comment by OlegForce** [comment]
added
