### ISSUE TITLE
City Field Location - Customer and Equipment Address

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#122]
Please move the City field to the line with the State and Zip instead of with Address 1 and Address 2.

**Comment by tbstevens** [comment]
@creekridge - Looking on the prod server right now. The customer address section is 1 row. But the row is responsive based on the monitor size. If the screen resolution doesn't fit all fields horizontally in one row, it pushes those fields below into a 2nd row. This is the standard for responsive design. I don't believe this is an issue. If you agree, please close the issue with the gray button below. If not, feel free to respond.
