### ISSUE TITLE
View Application Filters not appearing in prod

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#123]
Issue
---------
Filters section of view application screen should include dropdowns or a search box for filters. They are not appearing on the production server (same browser and version).

Expected
------------
Filters should appear with dropdowns.

**Comment by tbstevens** [comment]
@psakia - Could you take a look at this? The dropdowns/column filtering is being done through jquery. Worked fine in my local environment and was working in prod. Now it is not. Still working in my local environment though.

**Comment by psakia** [comment]
I found some characters  ï»¿ at the very top left of the file  "jquery.dataTables.columnFilter.js" which cause syntactical errors and prevent the rest of the functions to be loaded properly.
This file  "jquery.dataTables.columnFilter.js" seems was accidentally edited during delivery process to Creek Ridge production environment.
Let's remove these characters and test.

**Comment by tbstevens** [comment]
@Creekridge - I'm not seeing these issues anymore on the prod server but please confirm.

**Comment by Creekridge** [comment]
Tom,

Same result when you hit the site from http://www.vendorservicesgroup.com as before – no ability to filter:
[cid:image001.png@01D02F0A.6E851BE0]

From inside – crcvip:8080, it does work.

Until it works from the domain address, I don’t consider this fixed.

Sandy Graves
IT Manager
O: 952.826.7884
F: 952.996.0270
Sgraves@creekridgecapital.com<mailto:Sgraves@creekridgecapital.com>
www.creekridgecapital.com<http://www.creekridgecapital.com/>

[CreekridgeCapital_Standard_Color.jpg]





This email message is for the sole use of the intended recipients and may contain privileged and confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Although this email and any attachments are believed to be free of any virus or other defect, which might affect any system into which it is received or opened, it is the responsibility of the recipient to ensure that it is free from virus. The Sender and his/her employer accept no responsibility for any loss or damage arising in any way from its use.

**Comment by Creekridge** [comment]
@tbstevens filters work, however we have a few requests:
- Please eliminate the "Sales Rep" filter from Vendor Sales Rep's. They will not need this, only their managers.
- Can we have the filters in one horizontal line vs. stacked? All on same line as search bar?
- Eliminate the word "entries"

**Comment by tbstevens** [comment]
To keep it clean, I'll close this one out and recreate a new issue specific to the defect and cosmetic requests above.
