### ISSUE TITLE
Redirect vendor users to their main site page when hitting main portal page

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#125]
Issue
-----------
When a vendor user is logged in, leaves the site but is still logged in, and goes back to the primary portal url (where they'd usually log in), they are presented with a portlet informing them they are logged in with no additional options.

Expected
-------------
Similar to the login redirect, all vendor users (Site Admin, Sales Rep, Sales manager) should be redirected to their primary private page url (View Applications).

**Comment by psakia** [comment]
@tbstevens . I have added a jsp hook to login portlet. I tried to check in but I got message I'm not authorized to commit. I have sent attachment of the hook project.
Thanks

**Comment by psakia** [comment]
Hi Tom
Please see the hook attachment.
Thanks,
Pius

**Comment by tbstevens** [comment]
@psakia - This is not working. When a user is logged in and closes Liferay but still has their browser open and goes back to the main portal page already logged in, it is now hitting an infinite loop where the page keeps loading but nothing is happening.

**Comment by tbstevens** [comment]
@Creekridge - previous issue was resolved. This is now deployed in prod. I tested this under salereptester on vendor1 by being logged in. closing my tab in the browser, opening a new tab to vendorservicesgroup.com and was redirected to the site. Also tested to redirect if I enter vendorservicesgroup.com/group without anything after that. Ready for testing.

**Comment by Creekridge** [comment]
Confirmed - works as described by tstevens in last comment.
