### ISSUE TITLE
PDF should be viewable in browser.

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#126]
Issue
-----------
PDF files are downloaded when clicked on and it required the user to have a pdf viewer.

Expected
------------
PDF files generated in the manage docs screen should be viewable from the browser instead of downloaded.

**Comment by Creekridge** [comment]
PDF from site above renders correctly when opened in Safari on iPad.

**Comment by tbstevens** [comment]
@Creekridge - Thanks Sandy. It appears the difference is that the pdf is opening in your browser in Safari. The manage docs is downloading a pdf and your tablet needs a pdf viewer. We will modify this to open as a pdf in the browser so the user doesn't need to have a pdf viewer downloaded on the tablet, smartphone or desktop.

**Comment by tbstevens** [comment]
@Creekridge - PDF files now open in the browser vs downloading. Ready for testing.

**Comment by Creekridge** [comment]
Confirmed Works in both IE and in Safari on iPad. QUESTION - How difficult would it be to open in a separate tab?  Right now, it opens in same tab and you have to click on the "back" to get back to the site.
