### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#127]
Question:
--------------
Are any additional steps required for Liferay to work appropriately with SSL? If so, please provide the steps that are necessary.

**Comment by psakia** [comment]
@tbstevens The followings are instructions on how to setup SSL in Liferay Portal;

1. Configure Tomcat container in server.xml
 Enable this connector in server.xml
    <Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true"
               maxThreads="150" scheme="https" secure="true"
               clientAuth="false" sslProtocol="TLS" />
  
    
2.Liferay portal-ext.properties
Add/update file "LIFERAY_HOME/portal-ext.properties" with the following properties :
company.security.auth.requires.https=true
web.server.protocol=https
session.enable.phishing.protection=false

3. SSL certificate on Creek Ridge server JRE 
Generally all certificates available in jdk1.xxx\jre\lib\security location and server will always search the certificates from this location.

**Comment by tbstevens** [comment]
@Creekridge - We can walk through the instructions above if needed when you are ready to move to https

**Comment by Creekridge** [comment]
Do I need to request it as a “TomCat” or “Microsoft IIS” server?
[cid:image001.png@01D03F01.4E6A4950]

Sandy

**Comment by kdolan12** [comment]
@Creekridge These are instructions to setup the certificate directly in Tomcat.  There is really 2 ways we can do this:

1) We can setup Tomcat to receive the HTTPS requests directly.  I.e., setup the certificate on Tomcat as instructed above.
2) If we use IIS, we will need to configure the "JK Connector" to then have IIS forward requests on to Tomcat.

Sandy - We have a meeting tomorrow and I can talk to you about both options then.  If you want to jump on this sooner, i can meet with you first thing in the morning too.

**Comment by Creekridge** [comment]
Few questions:
1 - I generated the CSR and put the keystore in the jre7/bin location, not the jdk1.xxx\jre\lib\security location.  Do I need to recreate the keystore in the jdk1.xxx\jre\lib\security location?
2 - I'm assuming that generating a CSR from either of the location above would create the same CSR.  Any ideas if this is correct?
3 - Where is the server.xml file that I'm supposed to "Enable this connector in server.xml"?

**Comment by Creekridge** [comment]
Oh - also, do I need to restart anything for the above changes to start working?

**Comment by psakia** [comment]
@creekridge Please see the following answers;
1. Let's try to follow the initial instructions if don't work will try alternative. So let's put cert at jdk1.xxx\jre\lib\security.

2. The server.xml can be located at <Liferay_Home>\tomcat-xxx\conf\

Yes, you will need to restart
the server. Please make sure you don't forget to add the Liferay https settings in portal-ext. properties as the instructions.

Thanks,
Pius

**Comment by Creekridge** [comment]
@psakia & @tbstevens - Didn't work.  Can we set up a webex and work through it together?

**Comment by psakia** [comment]
Hi Tom/CreekRidge, Can you share any errors information you are getting? At least we can know which side it's failing Liferay or generated certificate itself?

**Comment by Creekridge** [comment]
Page not found.   And if you go to http:/www.vendorservicesgroup.com the public login page shows the hidden links.

**Comment by psakia** [comment]
Hello Sandy,
The information on the SSL setup instructions was for Liferay side with assumptions that you have created and imported to default server JRE folder indicated.

For generating ssl certificate I'm assuming you are using installed JFK key tool generator self-signed certificate.

Please find the following link with complete instructions on how to create self-signed certificate using key tool  and setting  SSL on tomcat server which is part of Liferay bundle.

https://www.liferay.com/web/meera.success/blog/-/blogs/liferay-portal-ssl-configuration

Sorry I'm in the location where i can not Webex

Thanks,
Pius

**Comment by Creekridge** [comment]
I have already created and imported the certs to the default server JRE folder indicated.

Yes, I used the Java keytool generator.

The only step included in this document that I hadn’t done is the path for the keystore file. https://www.liferay.com/web/meera.success/blog/-/blogs/liferay-portal-ssl-configuration.  I have now done added that and it still isn’t working.
