### ISSUE TITLE
Multiple emails in sales rep field

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#128]
Issue
------------
The Sales Rep custom field on the site is used to configure who should receive an email when an application is submitted. The PaymentCalculator.java method: submitApplication has code to email the Sales Rep but it does not allow for multiple email addresses.

Expected
------------
Allow administrators to configure multiple email addresses in the Sales Rep field using a semicolon as the delimiter. The submitApplication method should read all emails included from that field and email those users. Ensure that all recipients are emailed if one of the email addresses is invalid.

**Comment by psakia** [comment]
Please see the two attachments.

**Comment by psakia** [comment]
@tbstevens 
Tom, please see the two attached files PaymentCalculator.java and ManageDocument.java. I have seen bunch of conflicts, trying to play safe, so I would rather send as attachments via email.
Thanks

**Comment by tbstevens** [comment]
@Creekridge - You can now set the Rep Email custom field to be a comma delimited list of email addresses. Each email address in the comma delimited list will be emailed when an application is submitted within that vendor. Tested in prod and working. I'll let you confirm. I currently have Vendor2 setup under my two email addresses and you can modify that if you'd like.

**Comment by Creekridge** [comment]
Not working - I updated Vendor1 a few days ago with my addresses and when I just submitted an app, no e-mails were received.  I did receive notices at 11:35 from Vendor1 this morning from Tom.

**Comment by tbstevens** [comment]
@OlegForce - Could you look into why this is working if the application is submitted by an admin user but when submitted by a sales rep the comma delimited email is not working? The expectation is that the "Rep Email" custom field on the site can contain commas or semicolons between email addresses in one field. Each email address would receive an email. This works if the person submitting the application is an administrator. No emails are sent if submitted as a Sales Rep.

**Comment by OlegForce** [comment]
see #132 ... there is something crazy with custom fields permissions...

**Comment by tbstevens** [comment]
@Creekridge - Custom Fields permissions updates are complete. Retested this issue by submitting an application while logged in as a sales rep. It successfully emailed me at both of the email addresses included. To retest, just modify the Rep Email custom field for any vendor and include more than 1 email address by using a semicolon delimiter.

**Comment by Creekridge** [comment]
Confirmed it works.
