### ISSUE TITLE
Display message to call if pricing option has a rate factor set to 0

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#129]
Feature Gap
------------
There was originally a rule included in the design document that called for a message to be displayed to the user if the pricing option selected had a rate factor set to 0. This is Creekridge's method of flagging the record as a pricing option that requires the user to call and cannot complete the process online.

Expected
---------------
When displaying the "Pricing Overview" section that contains all of the pricing options meeting the criteria entered from the Payment Calculator, the following logic should be added:

1. If the pricing option has a rateFactor = 0 then

>a. Display the "Call us Message" instead of displaying the Payment Amount, Include in Proposal, and Use for Application columns for that record. The message should span those 3 columns.
>b. The "Call Us Message" should state: "Please call [RepName] at [RepPhone] for Payment Amount".
>c. The [Rep Name] and [Rep Phone] will be 2 additional custom fields on the site level (both text fields. Key names of "Rep Name" and "Rep Phone". Examples on prod site. These 2 fields will need to be retrieved and displayed in the call us message.
>d. If the RepPhone number is null or an empty string, default to displaying this message on all vendor sites: "Please submit a contact form for payment amount information on this pricing option." "Contact form" should be hyperlinked to the contact page "/group/[vendor]/contact".

Screenshot included below.
![phone number message](https://cloud.githubusercontent.com/assets/9217302/5684684/8b4684d8-97f8-11e4-8272-82c95d3d8a07.png)

**Comment by OlegForce** [comment]
@tbstevens could you clarify : we do not have a pricing option table. Purchase Option table does not have RateFactorRule. It's the other way around RateFactorRule has a Purchase Option.

**Comment by tbstevens** [comment]
Sorry. Intended to say proposal option which would have a rate factor.

**Comment by OlegForce** [comment]
give it a shot.

**Comment by tbstevens** [comment]
@Creekridge - This has been implemented. I have a test row in the prod server to test that the message appears. If you select "Financed Lease", "FMV", "48 months" it will product a row in the results that displays the message to call based on the custom fields.

FYI - The typical scenario for this based on your feedback is that it exceeds a specific dollar amount. When originally testing this, I couldn't get the message to show up as I was using a scenario with a higher dollar amount. This is due to a separate issue that I will be logging.

**Comment by Creekridge** [comment]
With the min dollar of $0 - I would agree that it works - but this isn't a valid scenario - I wouldn't set it up in the database if it wasn't a valid option.  I  did update my database to have a minprice of $0 rule with a factor and a second rule with a minprice of $10000 and the 0 ratefactor - this did not work.  It returned a payment.

**Comment by Creekridge** [comment]
Still working as indicated in last statement.

**Comment by tbstevens** [comment]
The issue causing this problem is related to #157. #157 has been fixed and tested in local environment. Awaiting additional changes before deploying to prod (awaiting 2nd half of doc gen changes before deploying so that doc gen doesn't break if deployed) and re-testing in prod. I'll keep this issue open and tied to #157 so both can be closed once it passes testing on prod.

**Comment by Creekridge** [comment]
@tbstevens  - is this ready to test again?

**Comment by tbstevens** [comment]
@creekridge - No. #157 is close to being resolved which is the reason this one is still open.

**Comment by tbstevens** [comment]
@OlegForce  - One more quick fix to make here. The requirements above ask for a different message to display if the Rep Name and Rep Phone aren't both setup for the vendor. If you get a null or blank value in those fields, it should display "Please submit a contact form for payment amount information on this pricing option.".

Instead it is displaying the same text but no name or phone. screenshot here.
https://www.dropbox.com/s/xnhozhbhmfjb74i/IncorrectMessageWhenNoValue.png?dl=0

**Comment by OlegForce** [comment]
Adjusted to account for empty string. Url for contact us form was there already, just did not check for empty string. No it should not show rep info if either phone or name are missing.

**Comment by tbstevens** [comment]
@Creekridge - tested and working in prod.

**Comment by Creekridge** [comment]
Confirmed show name and phone from Custom Fields or when Phone number blank to submit Contact Form
