### ISSUE TITLE
Move "Back to Credit App" and "Back to View Applications" to left side of screen under page title

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#131]
Issue
-------------
Back to Credit App and Back to View Applications buttons appear on the right side of the page.

Expected
-------------
They should appear on the left side under the page title. This aligns with button placement on other pages.

**Comment by psakia** [comment]
Tom,
Please see the attached view.jsp
thanks,
Pius

**Comment by psakia** [comment]
@tbstevens  Please see the attachment of view.jsp. I saw some conflicts, just to be safe.
Thanks

**Comment by tbstevens** [comment]
Closing issue -- will be related to request when making other changes to manage docs page.
