### ISSUE TITLE
Principal Info showing at top of the page in View-Only credit app

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#134]
Issue
-----------
Principal section showing up at the top of the page for credit app in view-only mode.

Expected
-------------
Should show up in correct place.

![image](https://cloud.githubusercontent.com/assets/9217302/5687223/08c7e6d8-9810-11e4-8ce6-d2a50919f1b7.png)

**Comment by OlegForce** [comment]
should work now. probably need to redo these two tables to be consistent with view app table.

**Comment by tbstevens** [comment]
@Creekridge - Ready for retesting in prod. Issue can be closed if it is no longer an issue.

**Comment by Creekridge** [comment]
@tbstevens looks like it's fixed.
