### ISSUE TITLE
Payment Calculator Not Showing

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#136]
I generated a proposal and sent a test email. The email went though. However, when I sent back to the payment calculator, I got a red error that said "Payment Calculator is temporarily unavailable."  Even two minutes later, after refreshing the page and visiting other pages in-between, the payment calculator is still not working.

**Comment by Creekridge** [comment]
Tested again:  Payment calculator does not work after an email has been sent (proposal or credit app).

**Comment by tbstevens** [comment]
@olegforce - Oleg, could this have something to do with session variables? If so, I can assign back to Pius.

**Comment by OlegForce** [comment]
try it now

**Comment by Creekridge** [comment]
@tbstevens not getting error anymore.
