### ISSUE TITLE
View Application Sales Rep filter and column

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#137]
Issue:
------------
If a user logs in as an admin, they get the expected functionality in the View Applications page. If from the same browser, you log out and log back in as a Sales Rep, you get the expected functionality. If you log out and log back in as an admin or sales manager, you no longer get the expected functionality. It seems to think the user is a Sales rep.

Expected
---------------
If the user logs out and a different user logs back in, it should work as expected for the role of the user currently logged in, regardless of who was logged in previously.

**Comment by tbstevens** [comment]
@Creekridge - This issue is now resolved in prod. The View Application screen show now work as expected for each role.

**Comment by Creekridge** [comment]
Not working - logged in as Salesreptester and can see all applications.

**Comment by tbstevens** [comment]
Closing as this is the same issue as #138
