### ISSUE TITLE
Sales Rep Tester Sees Everyone's Applications

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#138]
When I log in as SalesRep Tester, I see everyone's applications. I should only see SalesRep Tester's applications.

Only those at Sales Rep Managers and higher levels should see everyone's applications.

**Comment by tbstevens** [comment]
@Creekridge - Sorry, when I informed you last night regarding the new View Applications page having some additional functionality remaining that needed to be moved to the new version -- this piece was still outstanding. I'm going to leave this open to make sure it can be tracked.

**Comment by Creekridge** [comment]
@tbstevens sales rep tester still seeing all applications from everyone.

**Comment by Creekridge** [comment]
Note - admin (sandy) - doesn't see any - should see all

**Comment by tbstevens** [comment]
@Creekridge - retested and working after fix was made. The issue fixed was causing a problem across multiple issues and it is now resolved.

**Comment by Creekridge** [comment]
Still not working.

**Comment by tbstevens** [comment]
@OlegForce - Still an issue in prod. I'm unable to recreate this same issue in my environment. Was working in prod yesterday morning. No longer working. Nothing was deployed.

Reproduce
---------------
1. Login as salesreptester@test.com at vendorservicesgroup.com
2. Go to view applications. User is able to see all applications and sales filter.

If this cannot be reproduced, first login as an admin user, then login as a salesrep. This should cause the issue in production.

**Comment by OlegForce** [comment]
@Creekridge  error has something to do with chrome... do you see filters in browser when the issue occurs? Have you tried other browsers?

**Comment by tbstevens** [comment]
@OlegForce @Creekridge - 

Just to provide some more info Oleg - 

In both browsers, going to vendorservicesgroup.com results in the sales rep being able to see the sales rep filter, and they should not. In both browsers, the sales rep is seeing applications across all users.

If you log into the portal by remoting into CRCVIP and visiting localhost:8080 in Chrome you still get the issue of seeing applications across all users but an entirely different problem of the filters not appearing for all user roles.

If you use IE while in CRCVIP and localhost:8080, you get the same issues that appear in both browsers when viewing from vendorservicesgroup.com.

None of these issues are present in my local environment with the same set of code in either browser.

Based on this, it appears there is a browser issue causing something when you view it from the remote server via localhost:8080 but this is not occuring when you view it through vendorservicesgroup.com. However, it is a consistent issue in prod across all browsers, even when remoting in through localhost, that sales reps are able to see the sales rep filter field (they shouldn't be able to), and they are able to see applications across all users (they shouldn't be able to).

**Comment by tbstevens** [comment]
@Creekridge - I think we FINALLY may have resolution on this one! I'm not promising anything considering its history but I logged in as a sales rep, sales manager, and admin and saw expected results in internet explorer and chrome. Please confirm.

**Comment by Creekridge** [comment]
Logged on as SalesRep and can only see the SalesRep Apps.  Looks like it's working correctly.
