### ISSUE TITLE
View Applications Page - Buttons Not Working

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#139]
When logged in as a SalesRep Tester, the Actions: View, Edit and Docs do not work. The Cancel button does work.

**Comment by Creekridge** [comment]
@tbstevens I'm guessing this has something to do with how these applications were inputted in when the site was last updated. When I created one from scratch, these buttons worked.

**Comment by Creekridge** [comment]
@tbstevens Still and issue. Buttons do not work when logged in as sales manager.

**Comment by Creekridge** [comment]
@tbstevens When logged in as Sales Manager, blue New Application button does not work.

**Comment by tbstevens** [comment]
@Creekridge - Could you take another look at this? Let me know if you still see any issues. I removed the data moved from the old vendor site and it seems to have eliminated the issues caused by this.

**Comment by Creekridge** [comment]
@tbstevens buttons working now. Thanks!

**Comment by Creekridge** [comment]
@tbstevens we take that back. After loggin in and out between Manager and Rep testers, these buttons no longer work again...

**Comment by tbstevens** [comment]
@OlegForce - Getting a 302 Not Found if I'm logged in as a Sales Rep or Sales Manager when clicking on the buttons in the View Application screen.

payment-calculator?creditAppId=1301/group          302 Not Found

When I'm logged in as an admin, it works fine.

payment-calculator?creditAppId=1301/group/vendor1          200

**Comment by OlegForce** [comment]
per our conversation earlier, this should be working now.

**Comment by tbstevens** [comment]
@Creekridge - This should no longer be an issue. The issue was specific to vendor users because it was due to the redirect from login. The URL was missing a "/" at the end of the URL which broke the navigation on all the buttons for Sales Manager and Sales Reps. It was working for admins because they didn't get redirected. I confirmed it was working in prod but I'll make sure to let you confirm.

**Comment by Creekridge** [comment]
Buttons are now working when logged on as SalesManager and SalesRepTester.  However, when I log in as me (Sandy/admin).  I'm not seeing any existing apps or buttons.  I should be able to see them all.

**Comment by Creekridge** [comment]
Now able to see all apps when logged in as admin.  All buttons work.
