### ISSUE TITLE
Site Locks Ups / View Application screen issues

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#142]
I was logged in as a Sales Manager and Sales Rep at the same time. When going in the Sales Manager Site, the Payment Calculator did not work and View Applications did not show after I moved around the site for a while.

**Comment by tbstevens** [comment]
I am now experiencing the same issue where the View Applications page is not displaying any records. Assigning this one to @olegforce as high priority. It's a blocking issue for testing. It was displaying records last night.

**Comment by tbstevens** [comment]
@Creekridge - Could you re-test this and see if you can recreate the issue? I was unable to recreate it after removing the bad data.

**Comment by Creekridge** [comment]
@tbstevens haven't had any issues with this as I've been testing this AM. Will let you know if they should pop up again...
