### ISSUE TITLE
Manage Docs Page - View Does Not Work in FireFox

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#144]

**Comment by tbstevens** [comment]
@Creekridge - Could you provide more description here? Are you unable to download on the download link? Is this an issue that would be redundant to fix if the enhancement to do one click goes through? Just trying to figure out the details on how to prioritize the issue. Thanks!

**Comment by tbstevens** [comment]
@psakia - Pius, could you make sure the Manage Docs screen is displayed the same way in Firefox as it is in Chrome and IE?

**Comment by tbstevens** [comment]
Closing issue -- will be tied to request when modifications are needed as part of changes to doc generation.
