### ISSUE TITLE
Remove "Drafts" and add "All" to Status dropdown on View Applications screen

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#147]
Issue:
-----------
Status dropdown displays "Draft" and is missing "All" from dropdown.

Expected:
------------
Status filter dropdown should include: "Saved" (Default option), "Submitted", "Cancelled", and "All". Selecting "All" would show apps in Saved, Submitted, and Cancelled status. "Draft" status should never appear in View Applications screen.

**Comment by Creekridge** [comment]
@tbstevens looks good.
