### ISSUE TITLE
Remove My Sites option from dockbar for Site roles

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#150]
Enhancement Request
--------------------------------
For site role users (Site Admin, Sales Manager, Sales Rep), remove the My Sites dropdown from the blue dockbar. Users will be redirected to their site and it is unnecessary.

**Comment by tbstevens** [comment]
Tested in prod. @Creekridge - Assigned to you to confirm.

**Comment by Creekridge** [comment]
Confirm SItes on Dockbar no longer visible.  However it appears that all users are being redirected to the Creekridge generic login and not the site specific one.

**Comment by tbstevens** [comment]
@Creekridge - Do we want to add the logout customization as an additional enhancement? The logout function is native in Liferay and would require a similar "hook" that was used for the redirect at login. The logout as it exists right now, as you mentioned, takes the user back to the main portal login. Logging in would once again redirect them to their site. Same estimate as the login hook of 3 hours.

**Comment by Creekridge** [comment]
Please call to clarify.  What "hook for login" are you talking about.  The login isn't working correctly either.  It only takes me to the generic login.  When we discussed this, we said that we needed to be able to give out the site specific login OR the generic one.  Generic one defeats the purposes of private labeling.

**Comment by Creekridge** [comment]
Please call to clarify. What "hook for login" are you talking about?  Are you talking about the redirect from the login screen to the View Applications?

**Comment by tbstevens** [comment]
@Creekridge - I'll reach out tomorrow (1/21) in the late morning if that works for you. Around 10am?

**Comment by Creekridge** [comment]
Have another call scheduled at 10:30 and just got back from a meeting.  Maybe 11?
