### ISSUE TITLE
Remove My Profile and My Dashboard from User dropdown in dockbar

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#152]
Enhancement Request:
---------------------------------
Remove the My Profile option and My Dashboard option from the user dropdown in the blue dockbar for all users. The My Account and Sign Out options should still be present.

**Comment by tbstevens** [comment]
Tested in prod. @Creekridge - assigned to you to confirm.

**Comment by Creekridge** [comment]
Confirmed.
