### ISSUE TITLE
Sales Rep filter should not appear for Sales Reps

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#153]
Issue:
-----------
When logged in as a sales rep, sales rep is able to view the Sales Rep filter dropdown.

Expected
--------------
Sales rep should only have a status dropdown. 
Sales rep should only be able to see applications they created and should not have the ability to view others.

Recreate:
-------------
1. Go to www.vendorservicesgroup.com
2. Login as salesreptester@test.com
3. Go to view applications.
4. User is able to see other applications and user has a Sales Rep filter.

**Comment by tbstevens** [comment]
@OlegForce - Sorry, after the latest updates it looks like the Sales Rep filter is now not appearing for any users in prod. I tested this from several different browsers with no sessions or cache.

**Comment by OlegForce** [comment]
this should be working now.

**Comment by tbstevens** [comment]
Tested in prod.
