### ISSUE TITLE
Price is not being used correctly with Rate Factor Rules table

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#157]
Issue
-------------
1. Products are appearing in the Payment Calculator before entering a price.
2. Pricing Overview section is displaying results where the rate factor isn't properly being retrieved from the RateFactorRule table.
3. There are empty records being populated in the ProposalOption table when pressing Payment Calculator button.

Details to be added after researching fix.

**Comment by tbstevens** [comment]
@OlegForce  - Email sent with additional details.

**Comment by tbstevens** [comment]
Awaiting updates to Manage Docs UI before loading to prod server

**Comment by tbstevens** [comment]
@OlegForce - The updates didn't resolve the issue. If you take a look at this in prod, for Vendor1, there is a scenario setup with a rateFactor=0 at the minPrice of 1,000,000. If you were to enter an equipmentPrice of 1,000,000 and select all products, purch options, and terms, and click calculate payment, the last record should display with a message to call in for rates. Instead, it is still selecting the record with a minPrice of 750k instead of 1,000,000. 

The expectation is to return the records with a minPrice <= equipmentPrice

**Comment by tbstevens** [comment]
@Creekridge - Tested and working in prod now. Under Vendor1, there is a series of rules for the following combination: Product = 0% for 6 months, Purchase Option = $1 out, Term = 24 months.

The following rules are setup at different minPrices. I tested 4 of the price levels to be accurate. Please confirm.

MinPrice: $0   RateFactor: 0.007
MinPrice: $25000   RateFactor: 0.003
MinPrice: $50000   RateFactor: 0.004
MinPrice: $100000   RateFactor: 0.008
MinPrice: $750000   RateFactor: 0.02
MinPrice: $1000000   RateFactor: 0

**Comment by tbstevens** [comment]
@Creekridge  - I will log a separate issue related to disbling the Continue button from the Payment Options section if the only record returned is an option with a rate factor = 0 so that we can close this issue if it met the criteria related to this fix.

**Comment by Creekridge** [comment]
Tested with Vendor1 and FMV 48 months - I updated database for 3 minprice levels.  It works.
