### ISSUE TITLE
Cannot Calculate new payment options if the Application is saved and required fields aren't populated

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#158]
Issue:
--------------
User clicks to edit an existing application. Modifies information in the payment calculator section and pressing payment calculator button results in validation errors based on Save Validation.

Expected
----------------
The payment calculator button should not require all required fields be entered to simply modify the payment calculation and pricing options.

**Comment by tbstevens** [comment]
Original comment from Creekridge:
I've been testing and when I Edit a Saved Application that doesn't have all the Required fields populated, it doesn't let me recalculate the options. Instead it gives an error about all the required fields. Is there any way to have the "calculate payments" button just check the Payment Calculator fields and not the entire application when you click on Calculate payment?

**Comment by OlegForce** [comment]
I removed validation on calculate payment and move to customer info, but be aware that continue button saves application and that could be a way for users to skip validation rules.

**Comment by Creekridge** [comment]
Tom – please call to discuss options – I need to understand the repercussions of “skipping validation rules”

Sandy Graves
IT Manager
O: 952.826.7884
F: 952.996.0270
Sgraves@creekridgecapital.com<mailto:Sgraves@creekridgecapital.com>
www.creekridgecapital.com<http://www.creekridgecapital.com/>

[CreekridgeCapital_Standard_Color.jpg]





This email message is for the sole use of the intended recipients and may contain privileged and confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Although this email and any attachments are believed to be free of any virus or other defect, which might affect any system into which it is received or opened, it is the responsibility of the recipient to ensure that it is free from virus. The Sender and his/her employer accept no responsibility for any loss or damage arising in any way from its use.

**Comment by tbstevens** [comment]
@Creekridge - Ready to be retested. I can give you a call regarding the comment above. However, the comment is merely pointing out that when a user goes into the payment calculator section and modifies something, it won't validate, as requested. When they press Continue, it saves the application without validation per the existing functionality. However, if a user ever presses save or submit, it will always validate. Therefore, a user could never submit an application without it being validated. I don't think there is a downside to this but we can discuss. I'll send an email to find out when you are available.

**Comment by Creekridge** [comment]
Tom,

Please call – I had expected you to call and walk through the options on this request rather than proceeding with any changes when I logged it.

Sandy Graves
IT Manager
O: 952.826.7884
F: 952.996.0270
Sgraves@creekridgecapital.com<mailto:Sgraves@creekridgecapital.com>
www.creekridgecapital.com<http://www.creekridgecapital.com/>

[CreekridgeCapital_Standard_Color.jpg]





This email message is for the sole use of the intended recipients and may contain privileged and confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Although this email and any attachments are believed to be free of any virus or other defect, which might affect any system into which it is received or opened, it is the responsibility of the recipient to ensure that it is free from virus. The Sender and his/her employer accept no responsibility for any loss or damage arising in any way from its use.

**Comment by Creekridge** [comment]
Calculate and Continue to Customer Info working as expected.  Continue to Principal no longer validating.  Per conversation with Tom - it should be.

**Comment by tbstevens** [comment]
@Creekridge - Hi Sandy, I think there may have been a miscommunication. In our conversation, I stated that the Calculate Payments button will no longer validate as requested. I also informed you that the Continue to Customer & Equipment button will save the application but will not validate per existing functionality so the user is not stopped as they begin the process. The buttons that validate are Save, Save & Exit, and Submit. Continue to Principal does not validate (and didn't validate in the past). Is that the expectation? This would jump the user back as they work through the form.

**Comment by Creekridge** [comment]
Tom - there is no "Continue to Customer and Equipment" button on our live site - only :"Continue to Customer".  You indicated that only the "Calculate Payment" and "Continue to Customer" buttons were effected by this change.  I asked if any of the other Continue buttons would be affected - if they would still validate and you said "yes".    I honestly don't recall if "Continue to Principal" was validating previously or not.  I thought it was the last time I tested.

**Comment by tbstevens** [comment]
@Creekridge - Hi Sandy. It's actually simpler than that. The only thing impacted by this particular change was the Calculate Payment button. The change was that the Calculate Payment button no longer validates the application when you click on it. 

Everything outside of that particular change was just discussion around the existing functionality of the form and a a better understanding of when the form does and does not save/validate.

Calculate Payment button - **No validation (this was the change that was made)**, no saving
Continue to Customer - No validation but it saves the application because that particular option transitions from calculator to credit app.
All other continue buttons on the form - No validation, no save.
"Save" & "Save & Exit" - Validation and Save.
Submit - Validation and Submission.
Manage Docs - Validation, Save, and takes user to Manage Docs.

For the purpose of this modification, I believe we are okay to close the issue. The calculate payment button is now no longer validating when you click on calculate payment. I will hold off on closing until further response.

Thanks.
