### ISSUE TITLE
Calculate Payments are not giving expected Payment amounts

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#159]
Tested 48 month FMV Financed Lease at 8000 and 15000.  Have Ratefactor rule of .025 for minprice $0 and .07 for minprice $10000.
Payment Calculator results:
8000 = $170.15
15,000 = $319.80
However, if I take the cost times the factor I get:
8000 * .025 = $200
15000 * .07 = $1050

Pretty significant difference here - are you doing a different type of calculation - is the factor actually a yield?  Please explain.

**Comment by tbstevens** [comment]
The current calculation is (Equipment Price / Term in Months) * (1 + Rate Factor) as the Monthly Payment. Please let me know if this incorrect. If not incorrect, I'll close this issue as it is related to Issue #157 which is causing this to pull the wrong rateFactor as it is not using MinPrice correctly.

**Comment by tbstevens** [comment]
FYI - Very quick change to modify this calculation if we need to.

**Comment by Creekridge** [comment]
This is incorrect.  It should be Cost * factor.  I already incorporate the Term when I calculate the factor and I’m not sure why you’re adding 1 to it.

Sandy Graves
IT Manager
O: 952.826.7884
F: 952.996.0270
Sgraves@creekridgecapital.com<mailto:Sgraves@creekridgecapital.com>
www.creekridgecapital.com<http://www.creekridgecapital.com/>

[CreekridgeCapital_Standard_Color.jpg]





This email message is for the sole use of the intended recipients and may contain privileged and confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. Although this email and any attachments are believed to be free of any virus or other defect, which might affect any system into which it is received or opened, it is the responsibility of the recipient to ensure that it is free from virus. The Sender and his/her employer accept no responsibility for any loss or damage arising in any way from its use.

**Comment by tbstevens** [comment]
got it. Thanks.

**Comment by tbstevens** [comment]
Opening new issue related to this.
