### ISSUE TITLE
Update calculation for monthly payment amount

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#160]
Requirement Correction
--------------------------------
The calculation to determine the monthly payment amount needs to be updated to the following:

Equipment Price entered * RateFactor.

The RateFactor configured for the matching record (matching productId, purchaseOptionId, termId, vendorId, and minPrice) already incorporates the term into the rate factor and does not need to be included in the calculation.

**Comment by tbstevens** [comment]
Previous requirement incorrectly assumed the configured number would be applied similar to an interest rate or apr.

**Comment by tbstevens** [comment]
@Creekridge - Payment amount now reflects EquipmentPrice * rateFactor

**Comment by Creekridge** [comment]
Calculation is now correct, but still not recognizing when there is a second tier - ex: Minprice 0 = .05, minprice 10,000 = .03 - both values/calculations give result with .05 calculation.

**Comment by tbstevens** [comment]
Closed this issue. There is a separate issue logged regarding the minprice issue. This issue was related to the ratefactor calc.
