### ISSUE TITLE
Open PDFs in new browser

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#162]
To provide estimate to creekridge

**Comment by tbstevens** [comment]
@Creekridge - Simple fix to open doc in new browser for the manage docs page, but could take up to 2 hours to make the change in the Marketing Materials and Reports pages as they are part of a customized hook and the anchor tag is emedded within a Liferay tag. It's doable, just a little more work than the other page.

**Comment by tbstevens** [comment]
@Creekridge - Dev was able to find method that made this a very small change (minutes) that he was able to modify while making the logout changes to the hook.

**Comment by Creekridge** [comment]
Confirmed it works.
