### ISSUE TITLE
Logout redirect user to vendor branded login

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#164]
Awaiting decision from Creekridge on whether to move forward with logout hook for vendor branded logout.

**Comment by Creekridge** [comment]
@tbstevens - Please proceed.

**Comment by tbstevens** [comment]
@psakia - Pius, we need to add additional logic to the hook so that vendor users are redirected to their vendor branded login page after logging out from the vendor site.

Current functionality (out of the box)
--------------------
- Users are redirected to the main portal page after logging out.

Desired functionality
----------
- Users are redirected to the public login page on the vendor site but with the correct URL parameters to be redirected to the private home page after login.
- Taking users to the http://[domain]/group/[vendor]/ URL when logged out will properly redirect them to the public page with the redirect parameters needed to direct the user back to the private page after logging in.

Setup needed to create correct environment:
-------------
1. Vendor site in dev environment should have private pages.
2. Create one public page titled "Login". Drop the sign in portlet on this page and nothing else.

Acceptance Criteria:
----------------------------
1. Demonstrate that vendor users (Site Admin, Sales Reps, Sales Managers) are redirected to to the http://[domain]/group/[vendor]/ page when logging out from their site.
2. Demonstrate that users are directed back to the primary private page of the site when re-logging in from the location provided above.

@psakia - Let me know if you have any questions on this.

**Comment by psakia** [comment]
@tbstevens in Acceptance Criteria you have included Site Admin. I thought this is only applicable to site-roles? Also at 1# you specified the landing logout page to be http://[domain]/group/[vendor]/ page 
Do you actual mean http://[domain]/web/[vendor]/Login.? note the difference  between "/web" and "/group". Because in the above Setup section  you wrote " Create one public titled "Login". I'm assuming this a site specific branded public page.  Please clarify.

**Comment by tbstevens** [comment]
Hey @psakia - I think you accidentally closed this issue when you commented. I reopened it.

There are portal admins, and site admins. Any site level user should be redirected to their site login page.

The "/group/" instead of "/web/" is not a mistake. If you look at the behavior of liferay, if a user attempts to hit a private page, it will direct them to the public page with the correct redirect URL params. For example: 
1. Sign out on vendorservicesgroup.com.
2. Go to www.vendorservicesgroup.com/group/vendor1
3. Liferay automatically redirects you to http://www.vendorservicesgroup.com/web/vendor1/login but includes the URL params ?p_p_id=58&p_p_lifecycle=0&_58_redirect=%2Fgroup%2Fvendor1

Alternatively, you could redirect them specifically to that location, however, I don't believe this is the best solution because the other solution allows Creekridge to name the page whatever they want and you still maintain the redirect so that the user is taken to the private page after logging in.

**Comment by tbstevens** [comment]
@Creekridge - Working in prod. Ready for testing.

**Comment by Creekridge** [comment]
Confirmed.
