### ISSUE TITLE
Disable "Continue to Customer Info" button in Pricing Overview section if all records returned have rate factor = 0

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#165]
Issue
------------
When all the records displayed in the Pricing Overview section have ratefactor = 0 and require the vendor to call in for pricing, the user is still able to press the Continue to Customer Info button and submit the application.

Expected
--------------
If all options returned in the Pricing Overview section have ratefactor = 0, the Continue to Customer Info button should be disabled.

If at least one option returned in the Pricing Overview section has a rateFactor > 0, the Continue to Customer Info button should be enabled.

**Comment by OlegForce** [comment]
give it a shot.

**Comment by tbstevens** [comment]
@Creekridge - Tested in prod. You can use Vendor 1, 0% for 6 months, $1 out, 24 month term with an equipment price of 1 million to test the scenario of having 1 result that disables the button.

**Comment by Creekridge** [comment]
Confirmed with the above scenario.
