### ISSUE TITLE
Term Option Order

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#166]
Enhancement Request
--------------------------------
The term options in the payment calculator should always display in numerical ascending order (24 > 36 > 48 > etc) even as the options dynamically change based on other selections from the products and purchase options.

Original Question from Creekridge
-------------
when I was testing today, the term options weren't listed in numerical order - sometimes 48, 36, 24; other 24, 48, 36 depending on the items selected.  How difficult would it be to always show those in ascending numerical order - 24, 36, 48, 60?

**Comment by tbstevens** [comment]
@OlegForce - Before working on this one, could you provide an estimate for how much effort you believe it would be to make these always appear in numerical ascending order? Once approved, I'll relabel this as a Minor defect and let you know. Just looking for estimate on this one.

**Comment by tbstevens** [comment]
@Creekridge - Estimate is around 2-3 hours...a little more difficult based on how this dynamically gets populated and can change as selections are modified.

**Comment by Creekridge** [comment]
@tbstevens yes, please go head an have the term order in numerical order.

Thanks - Megan and Sandy

**Comment by tbstevens** [comment]
@OlegForce - Oleg, please proceed with this one.

**Comment by Creekridge** [comment]
@OlegForce  & @tbstevens  - we didn't specify, but we'd like ascending order (12, 24, 36, 48, etc) if we have the choice of ascending versus descending.

**Comment by OlegForce** [comment]
ascending it is then :)

**Comment by tbstevens** [comment]
@creekridge - This is ready for testing.

**Comment by Creekridge** [comment]
@tbstevens it's working. Thanks!
