### ISSUE TITLE
Customer Information didn't save when clicked on Manage Documents

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#167]
Entered New application straight through and clicked on Mange Documents to create Proposal.  Went back to Credit Application and all Customer fields now blank.

**Comment by OlegForce** [comment]
@tbstevens not able to reproduce in local env... help?

**Comment by tbstevens** [comment]
@Creekridge - Sorry, but could you see if you're able to recreate this again? If so, could you provide some steps? Our developer was unable to recreate this in the local environment and I was just unable to recreate this in production under both vendors. Tried a few applications. I created a new application, filled out all required fields, did not press save. Just pressed manage docs. Went to manage docs page and then clicked on the Back to Credit application button. Opened up the customer section and all details were there.

**Comment by Creekridge** [comment]
@tbstevens could not re-create
