### ISSUE TITLE
Clicking on Submit when no option selected looks like it doesn't do anything.

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#168]
Received error message, but due to window size, I had to scroll to the top of the window to see the error.  What are our options?  Can it be a pop-up that needs to be closed instead of at the top or when error ops up, takes you back to the top of the page?

Update 2/27/2015:
-----------
Make sure the "At least on option needs to be used on the application." error also moves the user back up to the top of the page.

**Comment by tbstevens** [comment]
@Creekridge - We can accomodate whatever error messaging you'd like to see here (with the understanding that it would take some additional time). This is following the same standard place other error messaging appears in the form. We could have the error message pop as a modal like the terms or whatever you'd prefer. Or we could simply look into forcing the screen to reposition to the top of the page as well.

**Comment by Creekridge** [comment]
Looking for the time estimates please.

**Comment by tbstevens** [comment]
@Creekridge - To shift the focus back up to the top of the page each time there is an error so the user is aware of the error messaging, would be about 1 hour of time across dev, unit test, and test in prod.

**Comment by Creekridge** [comment]
Please go ahead and do.

**Comment by tbstevens** [comment]
@OlegForce - Please proceed with this one.

**Comment by tbstevens** [comment]
@Creekridge - Ready for testing. It is now setup to shift focus back up to the top of the page where the error messaging is after receiving an error message. Tested while viewing bank references, principals (i.e. further down the page) by pressing Save or Submit with missing info.

**Comment by Creekridge** [comment]
@tbstevens looks like it's fixed. Thank you!

**Comment by Creekridge** [comment]
@tbstevens  - I just clicked on Submit without a "use on Application" selection and the page didn't refocus.  I was assuming it would when you had ANY data missing, not just field values.  How much time to fix?

**Comment by tbstevens** [comment]
@Creekridge - It would take appox 1 hour for dev, built, test. Please let me know if you'd like to proceed as soon as possible to fit it in before the weekend.

**Comment by Creekridge** [comment]
@tbstevens - Please proceed.

**Comment by tbstevens** [comment]
@OlegForce - Added update in the descrption above.

**Comment by tbstevens** [comment]
@Creekridge - Ready in prod.

**Comment by Creekridge** [comment]
@tbstevens  - refocus is now working.
