### ISSUE TITLE
Notifications on Blue Dock Bar

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#169]
@tbstevens, looks like the notifications on the blue dock bar have reappeared. Can you look into this as we'd like them to not show.

**Comment by Creekridge** [comment]
@tbstevens not seeing it anymore, once I created a new vendor site.

**Comment by tbstevens** [comment]
I had redeployed hook to see if that would take care of the issue as well. The timing may have been around the same time. I'll close it out.
