### ISSUE TITLE
Marketing Materials Not Opening in IE

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#170]
@tbstevens when I go to open marketing materials in IE, it does not work. It works in FireFox. Haven't tested any other browsers.

**Comment by tbstevens** [comment]
@Creekridge - What version of IE? I just tested in IE11 and it works. 

The previous request to modify the document libraries to open PDFs in the browser vs having them download as a file requires the user to have a pdf viewer built into the browser. All modern browsers have it built in including Chrome, Firefox, Opera, Safari, or IE10+. There are some known issues with IE versions older than 10. For those, the user would need a plugin for their browser. In the even a plugin wouldn't work, they could right click on the document name and save to their computer. This would be the same as the download option.

**Comment by Creekridge** [comment]
@tbstevens got it, thanks!

**Comment by Creekridge** [comment]
@tbstevens I was using IE10.

**Comment by tbstevens** [comment]
@Creekridge - Are we okay with closing this issue based on the information provided above or would you like some other recommended options that may require changes? Just wanted to make sure I didn't close anything that may not be resolved from your perspective.  Thanks.

**Comment by Creekridge** [comment]
@tbstevens ok to close
