### ISSUE TITLE
Continue to Customer Info. Button

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#173]
@tbstevens, when I click this button, it pulls the screen to the top to show that it's saved, which is OK. However, on the open section, it should the Customer Information section open, not the pricing options section.

**Comment by tbstevens** [comment]
@OlegForce - Oleg, can we make sure that the Customer Information section is the expanded section when a user clicks on the "Continue to Customer Info" button?

**Comment by tbstevens** [comment]
@Creekridge - Ready for testing

**Comment by Creekridge** [comment]
@tbstevens Fixed. Thank you!
