### ISSUE TITLE
Terms and Agreement Pop-Up

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#174]
@tbstevens when someone clicks the "Submit" button, the terms and agreement section needs to have "Creekridge Capital LLC" replaced with the Vendor name. For our private label programs, we cannot let people know we are Creekridge, even in the fine print.

**Comment by tbstevens** [comment]
@OlegForce - Please update the Terms & Agreement section to dynamically populate the Vendor's name based on the vendor name from Liferay site setup wherever it currently says Creekridge.

**Comment by tbstevens** [comment]
@Creekridge - Ready for testing.

**Comment by Creekridge** [comment]
@tbstevens Looks good. Thank you!
