### ISSUE TITLE
Deactiviate a Vendor Site

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#176]
@tbstevens is there a way to temporarily deactivate a specific vendor site, but keep all the information on it should they want the site back in the future?

**Comment by tbstevens** [comment]
@Creekridge - Yes. In Control Panel > Sites > Actions > "Deactivate". Once pressed, the site is no longer active. You can then activate through the same method.

**Comment by Creekridge** [comment]
@tbstevens thanks!
