### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#178]
@tbstevens just some small text changes to remain consistent on "Applications" vs. "Credit Applications". Please change:

- View Applications page heading to "View Applications" (remove Credit)
- View Applications page, please remove "applications" after Display drop down
- Manage Documents page, please change button to say "Back to Application" (vs. Back to Credit App)

Thanks!

**Comment by tbstevens** [comment]
@Creekridge - Ready for retesting on prod.

**Comment by Creekridge** [comment]
@tbstevens fixed. Thanks!
