### ISSUE TITLE
Creekridge Rep Login Page

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#179]
@tbstevens when I log in as a Creekridge Representative, it shows me a "page not found". Can we fix this to show all the vendor sites they are connected to?

**Comment by tbstevens** [comment]
@Creekridge - The Creekridge Manager needs to be assigned to the "Vendor Services Group" site. This private page of that site is the landing page for admins and Creekridge managers. The "page not found" error is based on the user logging in and not having access to private pages within that site. Vendor users would never see this because they are redirected to their one site. Let me know if you have any additional questions on this.

**Comment by tbstevens** [comment]
@Creekridge - I updated the existing creekridge manager test accounts so that they were added to the Vendor Service Group site. when you login under that user now, you should see it redirect to the site listing.

**Comment by tbstevens** [comment]
@Creekridge - ok to close this one out?

**Comment by Creekridge** [comment]
@tbstevens - you didn't assign it to us so we weren't aware it was ready to test.

**Comment by Creekridge** [comment]
@tbstevens still getting "Page Not Found" error.

**Comment by Creekridge** [comment]
@tbstevens I was trying to log in as Sheri Schneider

**Comment by tbstevens** [comment]
@Creekridge - Could you try and add Sheri as a Creekridge Manager user without an organization? The portal was not setup to use organization hierarchy. Organization hierarchy is typically what would be used on an internal portal for departmental users, not an external portal. Adding her as a user within an organization may be causing the login to behave differently. I'm unable to recreate when a user with the role of Creekridge Manager is setup without an Organization. If you are still getting page not found after creating her as a Creekridge Manager and tied to at least one site without an org, please let me know and we can determine if it is a bug.

**Comment by Creekridge** [comment]
@tbstevens do you recommend "User Groups" to keep users organized on the back end? I have Sheri as a Creekridge Manager and attached to the Homecare Homebase site. Still getting "Page Not Found" error.

**Comment by tbstevens** [comment]
@Creekridge - Could you email me the login for Sheri's account? I'm unable to recreate the same issue with other Creekridge Manager roles so to troubleshoot it looks like I may need her login. As far as user groups, that is an excellent way to arbitrarily keep users organized from an admin perspective. https://www.liferay.com/documentation/liferay-portal/6.2/user-guide/-/ai/user-groups-liferay-portal-6-2-user-guide-16-en

**Comment by tbstevens** [comment]
@Creekridge - RESOLVED! All Creekridge Manager's need to be assigned to the Vendor Services Group site as well as whatever other site they need to access. The vendor services group site is the landing page they hit and it's why it says page not found if they don't have access.

**Comment by Creekridge** [comment]
@tbstevens thanks for looking into that! 

Please close this issue.
