### ISSUE TITLE
What folder actually contains the website files?

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#180]
@tbstevens  - I'm setting up a security scanning service to help prevent hijacking and malware being inserted into the site (service is called SIteLock) and it requires ftp access to the folder where the website files for my domain are stored.  I'm assuming it's C:\portal\liferay-portal-6.2-ce-ga2, but from there does it go under Tomcat or something else.

**Comment by tbstevens** [comment]
Once code is deployed it moves into this folder: ...\liferay-portal-6.2-ce-ga2\tomcat-7.0.42\webapps

That webapps folder contains the files for each portlet, hook, and theme in liferay. 

The 3 folders within the webapps folder where we have custom code is:

Creekridge-portlet
VendorServicesGroupTheme-theme
CreekRidge-hook
