### ISSUE TITLE
Required Field Alert - Contact Phone

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#181]
When I tab off the Customer Contact phone, it doesn't turn red and give me the "This field is required message".  It is being checked upon save.

**Comment by tbstevens** [comment]
@Creekridge - Could you let me know what vendor you're using or try to recreate that same issue? I just logged in and went to vendor 1. I tabbed through the fields and it correctly shows me the field required message on that phone field as I tabbed through. There must be 

Screenshot:
https://www.dropbox.com/s/8ks7z6rxrusb8r1/customer%20contact%20phone.png?dl=0

**Comment by Creekridge** [comment]
@tbstevens - we're setting up the first real site - Homecare Homebase
![required field](https://cloud.githubusercontent.com/assets/9805551/6355652/2195eeb8-bc1d-11e4-968e-95e1f4ec2a41.jpg)

**Comment by tbstevens** [comment]
@Creekridge - Odd. I just went in and created an app (and canceled it) and received the message correctly in that site as well (screenshot below). I also went into the app you created, wiped out the phone number, hit tab and got the message. I can assign it but I'm worried they won't be able to recreate it to catch where the issue lies.
https://www.dropbox.com/s/2xihgh7sovnex8z/PhoneMessage.png?dl=0

**Comment by tbstevens** [comment]
@Creekridge - Figured out the issue. Works in chrome. Doesn't work in IE. I'll assign it.

**Comment by tbstevens** [comment]
@OlegForce  - Looks like some of the required field messaging when tabbing off the field is working in Chrome but not working in IE.

**Comment by OlegForce** [comment]
Which version of IE?

**Comment by Creekridge** [comment]
11

Sent from my iPhone

On Feb 24, 2015, at 7:05 PM, olegforce <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of IE?

**Comment by tbstevens** [comment]
@Creekridge - After looking into this a bit, I'd like to recommend we move this off the issue list.

1. There is no impact to the business requirement of informing users of a required field and preventing customers from submitting/saving without required fields. This is still working.

2. The impact is limited to the value added benefit of receiving a required message on tab-out. Furthermore, it's limited to only fields with formatting (SSN and phone). Even more, it is limited to only users on IE.

The technology used to provide the validation on tab-out is the jquery validation javascript library. There is also a formatting js library used for the field masking on SSN and phone. Both are pretty much gold standards and widely used for javascript libraries. There are some known issues across various browsers where small conflicts like this can occur.

The amount of time necessary to determine the fix and change the behavior for IE users would be fairly high as it would require modifying a standard js library.

Please let me know if you agree with moving this off the list. If you disagree, we can setup a quick call to discuss.

Thanks,

Tom

**Comment by Creekridge** [comment]
@tbstevens leave as is. thanks.
