### ISSUE TITLE
Customer Address2

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#184]
Customer Address2 appears to be auto-populating with the value of CustomerAddress1.  In my application, I left it blank, but when I go back in, it's populated.  I then CHANGED the value, Saved the Application and the value in Address2 changed back to the value in Address1

**Comment by tbstevens** [comment]
@OlegForce - could you take a look at this one?

**Comment by tbstevens** [comment]
Tested in prod and working.

**Comment by Creekridge** [comment]
@tbstevens works. thanks.
