### ISSUE TITLE
Replace site name with new custom field "Provider Name" in Terms & Agreement Modal

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#186]
Enhancement Request
------------------------------------
In the terms and agreement modal that the customer views upon submitting an application, the company name is currently based on the site name as configured in the Site Administration area of Liferay. For legal reasons, Creekridge needs the ability to set a Provider Name so that the company name in the terms & agreement modal can be unique from the actual portal site name.

Design:
----------
1. In the , termsAndAgreement.jsp file, replace any instance of "${siteGroup.name}" with the new "Provider Name" custom field value. Key = "Provider Name".

Addt'l Dev Env setup Info:
--------------
In your own environment, for unit testing, to create the custom field, go to Control Panel > Configuration > Custom Fields > Click on Site. Create a new Custom field under the key "Provider Name" as a text field.

**Comment by OlegForce** [comment]
added new field "Provider Name".

**Comment by tbstevens** [comment]
Tested and working in prod.

**Comment by Creekridge** [comment]
@tbstevens tested in homecare homebase. works on terms.
