### ISSUE TITLE
Enable new custom field to be used in doc gen templates

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#187]
Enhancement Request
---------------------------------
Current functionality limits Creekridge to displaying the vendor name based on the configured site name from the portal's site administration configuration screen in document templates. Creekridge would like the flexibility to modify the template to display a separate "Provider Name" field for certain clients.

Design
--------------
1. A new custom field on the Site object will be added to production under the key name "Provider Name".
2. This new "Provider Name" custom field needs to be made accessible to Creekridge within all doc gen templates under the name of [Provider Name].

Addt'l Dev Env setup Info:
--------------
In your own environment, for unit testing, to create the custom field, go to Control Panel > Configuration > Custom Fields > Click on Site. Create a new Custom field under the key "Provider Name" as a text field.

**Comment by divinami** [comment]
Implemented and checked in.

**Comment by tbstevens** [comment]
Tested and working in prod. Created a ProposalLetterTemplate-TestVendor1.html file in the new c:/portal/templates file location. Changed "[vendor name]" to "[Provider Name]". Added a Provider Name value of "Provider Name" in the custom field for Vendor1 site. Modified the custom field "Vendor HTML Template list" to use the new html file name for vendor1 from above. Generated a proposal letter and it generated with the Provider Name value instead of Vendor1. No build or deploy needed.

**Comment by Creekridge** [comment]
@tbstevens  - confirmed Provider name is loading to generated docs
