### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#189]
@tbstevens how do we know when a user requests to be added to a vendor site?

**Comment by tbstevens** [comment]
@Creekridge - Might make sense to have a call on this one tomorrow morning if you're available.

The last time we spoke I thought we hadn't quite landed on a solution as to whether users would self-register or admins would add users based on other enhancements that were larger in size to support self-registration into a specific site.

If self registration is still desired, there are 2 things to think about:

1. The user's experience in self registering
2. The admin's experience to understand when a user has registered.

For #1, there is no specific landing page built for a user with no role and no site assigned. Additional work would be needed to ensure a newly registered user is assigned a temporary user group or role and have that role land in a certain spot to inform them they must await being added to a site. The enhancement to have users who aren't admins or creekridge managers be directed specifically to one site may have to be tweaked to enable this -- we'd need to dig into it to find out. The suggestion would be to have a new user fall into a new role that we'd create titled "New Registration". We'd have to build a rule that directs a user of that role with no site assignment to a public page that informs them they will be notified when they are added to a site. This would require additional work.

For #2, there is no built in mechanism to alert an admin that a new user has registered. There is a built-in mechanism to assign new registered users to a specific role or user group from the control panel settings. With that quick change, it would at least give you visibility to any users who just registered (but you wouldn't be notified of it). If email notification is desired, an additional hook customization would need to be created to add logic to the registration process to email a specific inbox (or an inbox configured on a custom field).

In the meantime, if you didn't want the self registration available until these changes are made, we could turn off the self registration option and turn it back on at a later point through the control panel.

Please let me know how you'd like to proceed and if you'd like to meet on this one as it is probably requires additional discussion.

Thanks.

**Comment by tbstevens** [comment]
Update: Met with Creekridge on topic. They are aware of the options available and will get us information if they choose to move forward with any of them. For now, the "create new account" option from the login page is disabled. Users will have to request access to sites via other methods with system admins adding the user manually.

**Comment by Creekridge** [comment]
@tbstevens we figured out how we'd like to hand this. At this time, we don't need any help from you.  Thanks!!
