### ISSUE TITLE
Logos Missing

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#190]
@tbstevens the logos have seemed to vanish from all sites. We aren't even seeing the option on the pages to upload logos.  Help?

**Comment by tbstevens** [comment]
@Creekridge - Odd. The portal level setting must have been modified somehow. Control panel > Configuration > Portal Settings....scroll WAY down to logo. somehow the "allow site admin to use their own logo" was unchecked. checked it and turned it back on.
