### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#191]
@Creekridge - This is obviously low on the importance scale but I just thought I'd mention it: The favicon for the portal is currently the default liferay favicon. If there's a favicon you want displayed instead, I could make that modification pretty quickly (15 min or so). A favicon is the little icon that appears in the tab of every browser.

To create a favicon from another image: http://www.favicon.cc/

**Comment by Creekridge** [comment]
@tbstevens the liferay favicon is fine at the moment.  Thanks!
