### ISSUE TITLE
Pricing Option Selection to Docs

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#192]
@tbstevens  - In tweaking my documents, I decided to deselect 2 of my 6 pricing options in the "Include on Proposal" column.  When I generated the document, all 6 pricing options were printed.

**Comment by tbstevens** [comment]
@divinami - Hey Mike. In the Proposal Letter template, we need to make sure that only records with ProposalOptions.IncludeInProposal = True are presented in the Proposal Letter. It looks like its displaying all proposal options, regardless of whether the user chose to include them in a proposal letter (the purpose of that boolean field above). That was probably my miss in the original specs for you.

**Comment by divinami** [comment]
Fix checked into Git.

**Comment by tbstevens** [comment]
@Creekridge - tested in prod.

**Comment by Creekridge** [comment]
@tbstevens - confirmed working
