### ISSUE TITLE
Equipment Address fields not populating

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#194]
@tbstevens - When the "Equipment Address is same as Customer Location" is checked, the Equipment Address fields are not populating in the database or the documents.

**Comment by tbstevens** [comment]
@olegforce - could you modify the behavior to populate the hidden fields if same address is checked and make sure they save to the db?

**Comment by tbstevens** [comment]
@Creekridge - In prod, ready to test.

**Comment by Creekridge** [comment]
@tbstevens  - tested on new app - working.
