### ISSUE TITLE
Emails Not Working

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#196]
Issue Description
-------------------------
In the Manage Documents screen, there is an option to email a customer. Selecting email brings up the email popup screen but after submitting an email, no email is sent. The following error shows up in the tomcat stdout log:

20:25:40,665 ERROR [ManageDocumentPortlet:481] javax.mail.internet.AddressException: Illegal address in string ``''

Expected:
------------
1. Email should send if address is legitimate. It appears as though it is not picking up the email address entered in the form field.
2. If the email does not sent, user should receive message "There was an unexpected issue preventing this email from sending. Please contact the site administrator."
3. If the email does send, user should receive a success message "Email successfully sent" on the Manage Documents screen after email screen closes.

Original logged issue:

@tbstevens when I am on the Manage Document page and am emailing a document...the emails are not going through? Can you look at this? We consider this an urgent fix, please.

**Comment by tbstevens** [comment]
@divinami - Hey Mike - Not sure if you have any availability before the weekend. If not, feel free to assign this back to me and I can reassign. I know you didn't work on the email piece of the doc gen feature but I was hoping you might be able to take a look at this issue that is occuring in production for creekridge to see if you can resolve it. It looks like it isn't picking up the email address entered on the toAddress in the sendEmail.jsp. There was some new code added to allow for multiple email addresses to be entered in the toAddress and it would loop through them based on a delimiter of "," or ";". Looks like it loops through and moves them into an array on ManageDocumentPortlet.java starting at line 457. When there is one valid email address it isn't picking it up. Let me know if you need more detail.

**Comment by tbstevens** [comment]
@Creekridge - Deployed to prod. Tested by emailing myself a doc from vendor1.

**Comment by Creekridge** [comment]
@tbstevens  this is now working. Thanks!
