### ISSUE TITLE
Submit Button Email?

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#197]
@tbstevens when the green "Submit" button is clicked, this is not sending an email with the credit application information to the "Rep Email" we have in the custom fields. Please have this fixed on all vendor sites. We consider this an urgent fix. Thanks!

**Comment by Creekridge** [comment]
@tbstevens to clarify, we aren't receiving any email that the button was clicked.

**Comment by tbstevens** [comment]
@Creekridge - On the call it sounded like it is no longer an issue. Please confirm before I close it out.

**Comment by Creekridge** [comment]
@tbstevens  - I believe so.  We haven't tested since changing it from your email address, but since you were getting the emails, we should be good.

**Comment by tbstevens** [comment]
Sounds good. I'll close it out for now since I received that email today as proof that it is working.
