### ISSUE TITLE
Move Equipment Description textarea to left of Equipment Price

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#82]
Enhancement:
------------------
In the Equipment Information section, move the textarea for Equipment Description to the left of the defaulted Equipment Price Field. Equipment Price should appear to the right of the Equipment Description field in one line.

**Comment by Creekridge** [comment]
Or just below the Equipment Price and not below the Equipment Address

**Comment by tbstevens** [comment]
Duplicate
