### ISSUE TITLE
View Site in FireFox

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#91]
Site does not show up correctly when viewing in FireFox. Works in IE.

**Comment by tbstevens** [comment]
@Creekridge  - I'll take a look at this. I'm unable to install it on your server so I'll take a look on my own server later today to figure out what features aren't displaying correctly. The out of the box liferay portal is fine in firefox so I would assume it is a specific set of custom portlets that aren't displaying correctly?

**Comment by Creekridge** [comment]
@tbstevens, just the "View Applications" page isn't showing up correctly in FireFox.

**Comment by tbstevens** [comment]
@OlegForce - Oleg, it appears the View Applications page is not displaying as expected in Firefox and it is also not responsive on a mobile size. Any chance you could take a look at this screen to make it both responsive and display appropriately in versions that should be supported for Firefox, Chrome and IE?

**Comment by OlegForce** [comment]
this should take care of it.

**Comment by tbstevens** [comment]
Closing issue. Created one issue as a catch all for all view application improvements needed.
#117
