### ISSUE TITLE
View Application Page: Filters Box

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#94]
I'm not sure if we were planning on adding some functionality to this area, but if not, can we remove the grey filters box on the left-hand side? Not sure if we'd even need it anyways as the arrows and search can perform those functions...

**Comment by Creekridge** [comment]
We might be okay with the grey box being there if the filters actually worked.  Right now, it's a grey box with the labels, but no drop down/fill in options.  We also need to discuss which filter options are available - for example, I really doubt a sales rep is going to remember an app number to be able to search for it.

**Comment by tbstevens** [comment]
@Creekridge - I'm going to open a separate new related issue. My environment shows the filters just fine. It appears the filters section has an issue only on the production server. We'll need to figure out the cause.

**Comment by tbstevens** [comment]
Closed based on related issue being logged as a bug.
