### ISSUE TITLE
Payment Calculator: Not Saving Business Description and Requires clearing of pricing options to re-calculate.

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#95]
Original issue updated to text below [Tom]

Issue
----------
When a user attempts to save details entered on an app, the Business Description value is not saved.
In addition, when a user attempts to modify the equipment price and re-calculate, the user is forced to clear all pricing options as well.

Expected
----------------
1. Business Description value should be saved when pressing Save.
2. If the Equipment Price is changed, the user should be required to re-calculate before continuing, but the user should be able to re-calculate without having to also clear out the pricing options selected.

**Comment by Creekridge** [comment]
@tbstevens got it. However, if I change the price, the "Calculate Payments" button does not work, unless I uncheck and reselect pricing, product and term options. Any way to either have the "Calculate Payments" button work when new price is selected....or have pricing, product, terms remove options so I"m forced to reselect to calculate? As it is...it's kind of confusing...

**Comment by tbstevens** [comment]
@creekridge - Thanks for the update -- I'll modify the description of the bug up above.

**Comment by OlegForce** [comment]
Business Desc is now saved to db. I added reset action when amount is changed. Let me know if that will work.

**Comment by tbstevens** [comment]
@OlegForce  - Now when you change the Equipment price and tab off of it, it maintains  the previously selected pricing products, but it hides the purchase options and term fields forcing you to clear them and reselect them. The goal would be to allow them to change the price only and press calculate without having to reselect those options.

**Comment by OlegForce** [comment]
try it now.

**Comment by tbstevens** [comment]
Closed. Confirmed working in prod.
