### ISSUE TITLE
Generate Proposal: PDF Logo and Text

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#98]
Not sure if this isn't working, because the example "Vendor" does not have all info filled out...but on generated proposal the PDF isn't pulling the logo and some of the text/formatting is a tad off. I can get more specific when we meet on Thursday.

**Comment by tbstevens** [comment]
@kdolan12 @divinami - We will need to talk through this one.

**Comment by tbstevens** [comment]
@divinami - Mike, let me know if you have any questions based on Pius email regarding how to access the logo.

**Comment by divinami** [comment]
Fixed.

**Comment by Creekridge** [comment]
Tom - since we're revamping this- I'm assuming it's not ready to test - correct?

**Comment by tbstevens** [comment]
Closing issue -- replaced by request to update how doc generation currently works today.
