### ISSUE TITLE
Marketing Materials/Reporting: Remove Extra Screen

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#99]
Enhancement Request
--------------------------------
From the Marketing Materials and Reporting screens, documents should download when clicked on vs taking user to a preview screen.

Requirements
--------------------
1. Create a custom modification to the document library portlet to be used in the Reporting page and Marketing Materials page.
2. Modify the action taken when clicking on a document to download the document vs taking user to preview screen.
3. Customized portlet should maintain ability to configure portlet to open to a specific root folder of choice.

**Comment by tbstevens** [comment]
@Creekridge - Deployed to prod. Tested feature by adding some sample files to marketing materials folder in prod. Confirmed that clicking on link now opens directly to document. Also added sample file to reports folder and confirmed it is working from there as well.

**Comment by Creekridge** [comment]
Confirmed works from Marketing Materials and from Reporting as Admin.  Need to create folder/report to test as other users from Reporting - can I get a reminder on the process?  Have same question here as in PDF in Browser case - QUESTION: How difficult would it be to get it to open in a separate tab?

**Comment by tbstevens** [comment]
@Creekridge - I'll add this to our meeting topics.
